joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat: 20.0
  
teleop_node:
  ros__parameters:
    axis_linear:
      x: 0
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_linear:
      x: 0
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0